In [22]:
import tensorflow as tf

In [23]:
tf.__version__

'2.3.0'

In [24]:
tf.executing_eagerly()

True

In [25]:
x = [[2,]]

In [26]:
m = tf.matmul(x, x)#矩阵相乘

In [27]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [28]:
m.numpy()

array([[4]])

In [29]:
a = tf.constant([[1, 2],
                [3, 4]])

In [30]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [31]:
a.numpy()

array([[1, 2],
       [3, 4]])

In [32]:
b = tf.add(a, 1)# b=a+1

In [33]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [34]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [35]:
import numpy as np

In [36]:
d = np.array([[5,6], 
              [7, 8]])

In [37]:
d

array([[5, 6],
       [7, 8]])

In [38]:
(a + b).numpy()

array([[3, 5],
       [7, 9]])

In [39]:
g = tf.convert_to_tensor(10)

In [40]:
g

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [41]:
float(g)

10.0

In [42]:
c = tf.multiply(a, b)

In [47]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [48]:
num = tf.convert_to_tensor(10)

In [49]:
num

tf.Tensor(10, shape=(), dtype=int32)


In [51]:
for i in range(num):
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd
